"""Compile a Hugging Face causal LM to a Qualcomm Program Container (QPC).

Auto-generated by QUAD (mcp__quad__generate_code(platform="cloud", sdk="qaic",
deploy_target="qefficient")), unedited -- see ../README.md for why this
LLM-chat-shaped template doesn't fit Echo Chamber's actual need (an embedding
similarity-search service, not a chat model) and what signature_service.py
does instead.
"""

from __future__ import annotations

from QEfficient import QEFFAutoModelForCausalLM

MODEL_NAME = "signature_library_embed"


def compile_qpc(num_cores: int = 16, mxfp6_matmul: bool = True) -> str:
    """Compile ``MODEL_NAME`` to a QPC directory. Returns the QPC path."""
    model = QEFFAutoModelForCausalLM.from_pretrained(MODEL_NAME)
    qpc_path: str = model.compile(
        num_cores=num_cores,
        mxfp6_matmul=mxfp6_matmul,
    )
    print(f"[qefficient] compiled QPC -> {qpc_path}")
    return qpc_path


if __name__ == "__main__":
    compile_qpc()
