"""Generate text with a compiled QPC on Qualcomm Cloud AI 100.

Auto-generated by QUAD generate_code (platform=cloud, sdk=qaic,
deploy_target=qefficient), unedited -- kept as an audit record; not used by
Echo Chamber. See ../README.md.
"""

from __future__ import annotations

from QEfficient import QEFFAutoModelForCausalLM
from transformers import AutoTokenizer

MODEL_NAME = "signature_library_embed"


def main() -> None:
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = QEFFAutoModelForCausalLM.from_pretrained(MODEL_NAME)
    model.compile(num_cores=16, mxfp6_matmul=True)
    outputs = model.generate(
        prompts=["The Cloud AI 100 accelerator "],
        tokenizer=tokenizer,
    )
    print(outputs)


if __name__ == "__main__":
    main()
