"""OpenAI-compatible chat server wrapping QEfficient.generate() on Cloud AI 100.

Auto-generated by QUAD (mcp__quad__generate_code(platform="cloud", sdk="qaic",
deploy_target="qefficient")), unedited -- kept as an audit record; not used
by Echo Chamber (LLM chat serving, not embedding similarity search). See
../README.md and ../signature_service.py for the real implementation.
"""

from __future__ import annotations

from typing import Any

from fastapi import FastAPI
from pydantic import BaseModel
from QEfficient import QEFFAutoModelForCausalLM
from transformers import AutoTokenizer

MODEL_NAME = "signature_library_embed"

app = FastAPI(title="QUAD x QEfficient (Cloud AI 100)")

_model: Any = None
_tokenizer: Any = None


def _ensure_loaded() -> tuple[Any, Any]:
    global _model, _tokenizer
    if _model is None:
        _tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
        _model = QEFFAutoModelForCausalLM.from_pretrained(MODEL_NAME)
        _model.compile(num_cores=16, mxfp6_matmul=True)
    return _model, _tokenizer


class ChatMessage(BaseModel):
    role: str
    content: str | None = None


class ChatRequest(BaseModel):
    model: str
    messages: list[ChatMessage]
    max_tokens: int | None = 256


@app.post("/v1/chat/completions")
def chat(req: ChatRequest) -> dict[str, Any]:
    model, tokenizer = _ensure_loaded()
    prompt = "\n".join(f"{m.role}: {m.content or ''}" for m in req.messages) + "\nassistant:"
    outputs = model.generate(prompts=[prompt], tokenizer=tokenizer)
    text = str(outputs[0]) if outputs else ""
    return {
        "id": "chatcmpl-qeff",
        "object": "chat.completion",
        "model": req.model,
        "choices": [
            {"index": 0, "message": {"role": "assistant", "content": text}, "finish_reason": "stop"}
        ],
        "system_fingerprint": "quad-qaic-qefficient",
    }
