"""SNPE Python inference script for Arduino UNO Q (QCS2210).

Auto-generated by QUAD (Qualcomm Unified Agent for Developers)
via mcp__quad__generate_code(platform="linux", language="python", sdk="snpe",
runtime="cpu", model_path="models/echo_chamber_classifier.dlc") -- unedited.

NOT YET DEPLOYED OR RUN ON REAL HARDWARE. Per the architecture (see
../../ARCHITECTURE.md), the Arduino UNO Q's role in Echo Chamber is the
*primary listener* -- it streams SPH0641LU4H MEMS-mic audio to the X-Elite
host over the fusion WebSocket (see capture_agent.py alongside this file),
it does not run the classifier itself (2GB RAM / DSP V66 INT8-only headroom
is reserved for the mic capture + framing, not a second inference copy).
This generated inference.py is kept as the QUAD-standard on-device fallback
path (e.g. if a future revision moves classification onto the board) and as
a record of what generate_code produced for this target -- it has not been
adapted or exercised.
"""

import numpy as np

try:
    import snpe
except ImportError:
    print("SNPE Python SDK not found. Install from SNPE SDK package.")
    raise


def load_model(dlc_path: str, runtime: str = "dsp") -> "snpe.SNPE":
    """Load SNPE DLC model with specified runtime."""
    runtime_map = {
        "cpu": snpe.Runtime.CPU,
        "gpu": snpe.Runtime.GPU,
        "dsp": snpe.Runtime.DSP,
    }
    container = snpe.DlContainer(dlc_path)
    builder = snpe.SNPEBuilder(container)
    builder.set_runtime(runtime_map.get(runtime, snpe.Runtime.DSP))
    return builder.build()


def prepare_input(input_shape: tuple = (1, 3, 224, 224)) -> np.ndarray:
    """Prepare input tensor."""
    return np.random.randn(*input_shape).astype(np.float32)


def run_inference(model: "snpe.SNPE", input_data: np.ndarray) -> np.ndarray:
    """Execute inference on Hexagon DSP."""
    input_map = {"input:0": input_data}
    output_map = model.execute(input_map)
    return list(output_map.values())[0]


def main() -> None:
    """Main inference pipeline."""
    model_path = "models/echo_chamber_classifier.dlc"
    runtime = "cpu"

    print(f"Loading model: {model_path} (runtime: {runtime})")
    model = load_model(model_path, runtime)

    input_data = prepare_input()
    output = run_inference(model, input_data)

    top_class = np.argmax(output)
    print(f"Prediction: class {top_class} (score: {output[0][top_class]:.4f})")


if __name__ == "__main__":
    main()
